spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_agent?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: a6226487
    driver-class-name: com.mysql.cj.jdbc.Driver
